### ISSUE TITLE
[Bug] Visualization Mismatching Problem of 3D Lidar Box on imgs in NuScenes Dataset.

### ISSUE THREAD

**Issue by Irvingao** [open-mmlab/mmdetection3d#2607]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection3d/issues) and [Discussions](https://github.com/open-mmlab/mmdetection3d/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection3d.readthedocs.io/en/latest/notes/faq.html) but cannot get the expected help.
- [x] The bug has not been fixed in the version (0.17).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

branch https://github.com/open-mmlab/mmdetection3d/v0.17.3

### Environment
```bash
sys.platform: linux
Python: 3.7.13 (default, Mar 29 2022, 02:18:16) [GCC 7.5.0]
CUDA available: True
GPU 0,1: NVIDIA GeForce RTX 3090
CUDA_HOME: /usr/local/cuda-11.3
NVCC: Build cuda_11.3.r11.3/compiler.29745058_0
GCC: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
PyTorch: 1.9.0+cu111
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.1.2 (Git Hash 98be7e8afa711dc9b66c8ff3504129cb82013cdb)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.0.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.1, CUDNN_VERSION=8.0.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.9.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.10.0+cu111
OpenCV: 4.6.0
MMCV: 1.3.13
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 11.1
MMDetection: 2.14.0
MMSegmentation: 0.14.1
MMDetection3D: 0.17.0+ded7876
------------------------------------------------------------
```
### Reproduces the problem - code sample

```python
def draw_lidar_bbox3d_on_img(bboxes3d,
                             raw_img,
                             lidar2img_rt,
                             img_metas,
                             color=(0, 255, 0),
                             thickness=1):
    """Project the 3D bbox on 2D plane and draw on input image.

    Args:
        bboxes3d (:obj:`LiDARInstance3DBoxes`):
            3d bbox in lidar coordinate system to visualize.
        raw_img (numpy.array): The numpy array of image.
        lidar2img_rt (numpy.array, shape=[4, 4]): The projection matrix
            according to the camera intrinsic parameters.
        img_metas (dict): Useless here.
        color (tuple[int]): The color to draw bboxes. Default: (0, 255, 0).
        thickness (int, optional): The thickness of bboxes. Default: 1.
    """
    img = raw_img.copy()
    corners_3d = bboxes3d.corners
    num_bbox = corners_3d.shape[0]
    pts_4d = np.concatenate(
        [corners_3d.reshape(-1, 3),
         np.ones((num_bbox * 8, 1))], axis=-1)
    lidar2img_rt = copy.deepcopy(lidar2img_rt).reshape(4, 4)
    if isinstance(lidar2img_rt, torch.Tensor):
        lidar2img_rt = lidar2img_rt.cpu().numpy()
    pts_2d = pts_4d @ lidar2img_rt.T

    pts_2d[:, 2] = np.clip(pts_2d[:, 2], a_min=1e-5, a_max=1e5)
    pts_2d[:, 0] /= pts_2d[:, 2]
    pts_2d[:, 1] /= pts_2d[:, 2]
    imgfov_pts_2d = pts_2d[..., :2].reshape(num_bbox, 8, 2)

    return plot_rect3d_on_img(img, num_bbox, imgfov_pts_2d, color, thickness)

```

- `main.py` shows at below:
```python
                import cv2
                img = cv2.imread(kwargs['img_metas'][0]['filename'][0]) # front 
                r_h, r_w,_ = kwargs['img_metas'][0]['img_shape'][0]
                img = cv2.resize(img, (r_w, r_h))
                box = kwargs['gt_bboxes_3d'][0]
                lidar2img_rt = kwargs['img_metas'][0]['lidar2img'][0]
                plot_img = draw_lidar_bbox3d_on_img(box,
                                                    raw_img=img,
                                                    lidar2img_rt=lidar2img_rt,
                                                    img_metas=None,
                                                    color=(0, 255, 0),
                                                    thickness=1)
                cv2.imwrite("plot_lidar_img.jpg", plot_img)

```

### Reproduces the problem - command or script

- I use official `draw_lidar_bbox3d_on_img` code to visualize `GT LidarBoxInstance`, but got **mismatching problem**. It got height mismatching from ground.

#### **Mismatching images show as below:**

![image](https://github.com/open-mmlab/mmdetection3d/assets/58903762/ed80a079-65c0-4670-a8fa-e83b385f79ec)
![image](https://github.com/open-mmlab/mmdetection3d/assets/58903762/9436718e-8ca6-4853-920f-683e9ada0f34)
![image](https://github.com/open-mmlab/mmdetection3d/assets/58903762/f0f68719-c4ec-455a-8a50-8183d8223c20)

- It will be serious in long range small objects: 

![image](https://github.com/open-mmlab/mmdetection3d/assets/58903762/528aa9a4-f81e-4339-a5da-1a70467f96ca)

### Additional information

I want to know the reason of mismatching because I can't see it in the nuscenes dataset officical demo.

- Here is Nuscenes Dataset Annotation which is captured from [nuscenes websit](https://www.nuscenes.org/nuscenes?sceneId=scene-0061&frame=0&view=regular)

![image](https://github.com/open-mmlab/mmdetection3d/assets/58903762/04d7f923-95e1-459d-abe6-b4324570bbdc)

**Comment by JingweiZhang12** [comment]
Please use the main/dev-1.x branch which has few bugs.

**Comment by Irvingao** [comment]
Code Problems, resloved.

**Comment by DatDoc** [comment]
hi @Irvingao , how did you solve the problem? thank you
