### ISSUE TITLE
Progress of Chinese Documentation

### ISSUE THREAD

**Issue by ZwwWayne** [open-mmlab/mmdetection3d#699]
We are building Chinese Documentation now, PRs of translation from the community are welcomed.
To make the community fully aware of the progress, we list the progress here. Please feel free to leave a message and create a PR if you are willing to translate any one of the documentation. We suggest creating a PR for only one file.

- [x] docs_zh-CN/0_demo.md #745 
- [x] docs_zh-CN/1_exist_data_model.md #746 
- [x] docs_zh-CN/2_new_data_model.md #729 
- [x] docs_zh-CN/data_preparation.md #787 
- [x] docs_zh-CN/faq.md #730 
- [x] docs_zh-CN/getting_started.md #725 
- [x] docs_zh-CN/model_zoo.md #735 
- [x] docs_zh-CN/tutorials/config.md #788
- [x] docs_zh-CN/useful_tools.md #728 
- [x] docs_zh-CN/tutorials/customize_dataset.md #792 
- [x] docs_zh-CN/tutorials/customize_models.md #820 
- [x] docs_zh-CN/tutorials/customize_runtime.md #829 
- [x] docs_zh-CN/tutorials/data_pipeline.md #827 
- [x] docs_zh-CN/tutorials/waymo.md #859
