### ISSUE TITLE
Progress of Migration of CUDA ops to MMCV

### ISSUE THREAD

**Issue by ZwwWayne** [open-mmlab/mmdetection3d#994]
We are going to migrate CUDA ops in MMDet3D to MMCV, please feel free to review or give suggestions on them if you are interested.

Features:

- [x] open-mmlab/mmcv#1332
- [x] open-mmlab/mmcv#1337 
- [x] open-mmlab/mmcv#1338 
- [x] open-mmlab/mmcv#1354 
- [x] open-mmlab/mmcv#1355 
- [x] open-mmlab/mmcv#1356 
- [x] open-mmlab/mmcv#1357 
- [x] open-mmlab/mmcv#1358
- [x] open-mmlab/mmcv#1381
- [x] open-mmlab/mmcv#1382 
- [x] open-mmlab/mmcv#1581
